# nonparametric_dataset_cfg:
#   ticker: "SPXUSD"
#   platform: "MS"
#   timeframe: "M1"
#   original_data_path: "data/raw/${ticker}/DAT_${platform}_${ticker}_${timeframe}.csv"
#   valid_ratio: 0.10
#   test_ratio: 0.10

# parametric_dataset_cfg:
#   ticker: "SPXUSD"
#   platform: "MS"
#   timeframe: "M1"
#   original_data_path: "data/raw/${ticker}/DAT_${platform}_${ticker}_${timeframe}.csv"
#   valid_ratio: 0.10
#   test_ratio: 0.10
#   is_parametric: true

nonparametric_dataset_cfg:
  ticker: "AAPL"
  original_data_path: "data/raw/${ticker}/${ticker}.csv"
  valid_ratio: 0.10
  test_ratio: 0.10

parametric_dataset_cfg:
  ticker: "AAPL"
  original_data_path: "data/raw/${ticker}/${ticker}.csv"
  valid_ratio: 0.10
  test_ratio: 0.10
  is_parametric: true