nonparametric_dataset_cfg:
  platform: "MS"
  timeframe: "M1"
  valid_ratio: 0.10
  test_ratio: 0.10

parametric_dataset_cfg:
  platform: "MS"
  timeframe: "M1"
  valid_ratio: 0.10
  test_ratio: 0.10
  is_parametric: true

