nonparametric_dataset_cfg:
  ticker: "AAPL"
  original_data_path: "data/raw/${ticker}/${ticker}.csv"
  valid_ratio: 0.2
  do_transformation: true
  seed: 42

parametric_dataset_cfg:
  ticker: "AAPL"
  original_data_path: "data/raw/${ticker}/${ticker}.csv"
  valid_ratio: 0.2
  is_parametric: true
  do_transformation: true
  seed: 42